name: Create PR
on:
  # schedule:
  #  - cron: 55 * * * *
  workflow_dispatch:

jobs:
  create_pr:
    name: Make dummy changes and create a PR
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Make changes
        run:  printf "\n$(date)" >> README.md
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create a PR
        uses: peter-evans/create-pull-request@38e0b6e68b4c852a5500a94740f0e535e0d7ba54
        with:
          branch: pull-request-${{ steps.date.outputs.date }}
          title: Add newest date to README (${{ steps.date.outputs.date }})
          commit-message: Add newest date to README (${{ steps.date.outputs.date }})
          body: >
            This is an example PR description.

            It's multi-line!
          delete-branch: true
