name: Prod deployment

on:
  workflow_dispatch:
    inputs:

      commit-to-deploy:
        type: string
        description: Hash of a commit to be deployed - its CI has to be green!
        required: true

jobs:

  deploy_to_prod:
    name: Deploy to prod
    runs-on: ubuntu-latest
    environment: Prod
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          # Fetch all commits to know their hashes, but without their contents.
          filter: tree:0
          fetch-depth: 0
      - name: Authenticate with the machine user
        run: |
          git config --global credential.helper "" # disable the keychain credential helper
          git config --global --add credential.helper store # enable the local store credential helper
          echo "https://x-access-token:${{ secrets.MACHINE_USER_DEPLOYMENT_TOKEN }}@github.com" >> ~/.git-credentials # add credential to file
          git config --global --replace-all url.https://github.com/.insteadOf ssh://git@github.com/
          git config --global --add url.https://github.com/.insteadOf git@github.com:
      - name: Check out the prod branch
        run: git checkout prod
      - name: Hard-reset the prod branch to the desired commit
        run: git reset --hard ${{ inputs.commit-to-deploy }}
      - name: Force-push the prod branch
        run: git push -f
